[theme]
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 100

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[layout]
wideMode = true
